version: "3"

services:
  uwazi:
    build: ./
    working_dir: /home/node/uwazi
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - DBHOST=mongo
      - DATABASE_NAME=uwazi_development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - IS_FIRST_RUN=${IS_FIRST_RUN:-false}
    depends_on:
      - elasticsearch
      - mongo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    restart: unless-stopped
    command: elasticsearch -Expack.security.enabled=false -Ecluster.name=docker-cluster -Ehttp.port=9200 -Ehttp.cors.allow-origin="http://localhost:51000" -Ehttp.cors.enabled=true -Ehttp.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization -Ehttp.cors.allow-credentials=true
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data

  # dejavu "The Missing Web UI for Elasticsearch"
  # See https://github.com/appbaseio/dejavu
  # To configure, access http://localhost:51000 and use:
  #    http://localhost:9200
  #    uwazi_development
  elasticsearch-gui-dejavu:
    image: appbaseio/dejavu:latest
    ports:
      #- "1358:1358"
      - "51000:1358"
    depends_on:
      - elasticsearch

  mongo:
    image: mongo:3.4
    restart: unless-stopped
    volumes:
     - ./data/mongo:/data/db
     #- ./data/dump:/dump
    command: mongod --smallfiles
    # Don't expose unprotected mongo db to the world, needs to be accessible only from within docker network
    #ports:
    #  - 27017:27017
    logging:
      options:
        max-size: 10m
        max-file: '3'

  # Cross-platform and self hosted, easy to use mongodb management tool - Formerly Mongoclient
  # See https://github.com/nosqlclient/nosqlclient
  mongo-gui-mongoclient:
    image: mongoclient/mongoclient:latest
    volumes:
     - ./data/mongo:/data/db
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - 52000:3000

volumes:
  esdata1:
    driver: local



